### ISSUE TITLE
How to use JVM?

### ISSUE THREAD

**Issue by posxposy** [ibilon/testgenjvmandroid#1]
Hi!
Thank you for that sample!
A bit off-topic, but can you please explain how JVM target works?

I see you still generating Java sources for this sample by: https://github.com/ibilon/testgenjvmandroid/blob/master/build.hxml#L2

And general build steps look like the same what the existing Java target can do too.  So, what the benefit of JVM in that case (if you still need to generate Java sources)?

Is there a way to avoid generating Java sources? 

I tried to test JVM, so I've created an empty project with:
```hxml
-m Main
-D jvm
--java ./out
```
And with latest Haxe night build `-D jvm` has no effect. Did I'm missing something?

**Comment by ibilon** [comment]
That should work, what's the version of your nightly? Maybe it's slightly too old and doesn't contain the jvm target, it was added not even a day ago.

The target directly create the .class instead of .java and then bundle them in a .jar.

It also work much better when type parameters are involved, it's not easy to generate valid java syntax and there's a lot of weird cases due to casting, which doesn't happen when you output bytecode.

This has several advantages, it's faster since it doesn't go through the java compiler, which end up not necessary.

That last part isn't true of this repository which compile a java file generated by the android sdk,
this is only a proof of concept showing that the generated bytecode can be compiled to android bytecode. Though only for android 9 since it's java 8 byte code, this could be improved by modifying the jvm target to use older jvm apis.

**Comment by posxposy** [comment]
> That should work, what's the version of your nightly? Maybe it's slightly too old and doesn't contain the jvm target, it was added not even a day ago.

Oh that's explains everything :) Latest night build is:
`2019-05-10 11:04:29      6338014        haxe_2019-05-10_development_0f9bb3e.zip`

That's why I was confused by generated `.java` files. Will wait until the new night build will be available.


> Though only for android 9 since it's java 8 byte code, this could be improved by modifying the jvm target to use older jvm apis.

As I remember there was some compilation flag for supporting Java 8 sources on old Android versions. But not sure if this is a case for bytecode.

Thanks for helping!

**Comment by ibilon** [comment]
> Oh that's explains everything :) Latest night build is:
2019-05-10 11:04:29 6338014 haxe_2019-05-10_development_0f9bb3e.zip

That's one commit before the new target, bad luck :)

> As I remember there was some compilation flag for supporting Java 8 sources on old Android versions. But not sure if this is a case for bytecode.

Yeah my comment is not entirely accurate, java 8 can be used for older android, but not 100% of it (nor 100% of java 7), and the bytecode currently use some part of java 7 actually that aren't in the android virtual machine until 8 and one until 9.

**Comment by ibilon** [comment]
The rc3 was [released](https://community.haxe.org/t/haxe-4-0-0-rc-3-is-released/1808/3) so now it's easily available :)
Don't hesitate to open a topic on the forum if you have some questions about the target, or a github issue on [haxe](https://github.com/HaxeFoundation/haxe) if there is some problem.
